AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - 'config/initializers/devise.rb'
    - 'bin/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'script/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
Lint/DuplicateRegexpCharacterClassElement: 
  Enabled: true
Lint/EmptyBlock: 
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/ToEnumArguments: 
  Enabled: true
Lint/UnmodifiedReduceAccumulator: 
  Enabled: true
Style/ArgumentsForwarding: 
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/DocumentDynamicEvalDefinition: 
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true
Style/SwapValues: 
  Enabled: true
Style/Documentation:
  Enabled: false
